spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tsukumi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Boluo123
  data:
    cluster-name: elasticsearch
    cluster-nodes: 127.0.0.1:9300

encrypt:
  key-store:
    location: classpath:auntie-tsukumi.jks
    secret: Boluo123
    alias: auntie-tsukumi

security:
  ignore-urls:
    - /private/grumbles
    - /private/grumble
    - /user/register
    - /oauth/**