spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tsukumi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Boluo123
